sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pradeep1103/docker-react -f Dockerfile.dev .

script:
  - docker run pradeep1103/docker-react npm run test -- --coverage

