sudo: required
services:
  - docker
language: generic    

before_install:
  - docker build -t pradeep/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pradeep/docker-react npm run test -- --coverage
